language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest

# Transifex
sudo: required
after_success:
  - pip install virtualenv
  - virtualenv ~/env
  - source ~/env/bin/activate
  - pip install transifex-client
  - sudo echo $'[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = '"$TRANSIFEX_USER"$'\npassword = '"$TRANSIFEX_PASSWORD"$'\ntoken = '"$TRANSIFEX_API_TOKEN"$'\n' > ~/.transifexrc
  - tx push -s